automate_docker <- function(path = "."){
  if(automate_dir()){
    dockerfile_base <- paste0(getOption("repro.dir"),
                              "/",
                              getOption("repro.dockerfile.base"))
    dockerfile_packages <- paste0(getOption("repro.dir"),
                                  "/",
                                  getOption("repro.dockerfile.packages"))
    dockerfile_manual <- paste0(getOption("repro.dir"),
                                "/",
                                getOption("repro.dockerfile.manual"))
    # handle base
    if(!fs::file_exists(dockerfile_base))use_docker(file = dockerfile_base,
                                                    open = FALSE)
    # handle packages
    docker_packages <- use_docker_packages(
      yamls_packages(path = usethis::proj_path(path)),
      file = dockerfile_base,
      write = FALSE,
      append = FALSE
    )
    xfun::write_utf8(docker_packages, dockerfile_packages)
    # handle manual
    if(!fs::file_exists(dockerfile_manual))fs::file_create(dockerfile_manual)

    # bundle dockerfiles
    automate_docker_bundle()
  }
}

automate_docker_bundle <- function(file = "Dockerfile"){
  dockerfiles <- c(
    dockerfile_base = paste0(
      getOption("repro.dir"),
      "/",
      getOption("repro.dockerfile.base")
    ),
    dockerfile_manual = paste0(
      getOption("repro.dir"),
      "/",
      getOption("repro.dockerfile.manual")
    ),
    dockerfile_packages = paste0(
      getOption("repro.dir"),
      "/",
      getOption("repro.dockerfile.packages")
    )
  )
  note <- glue::glue("# Generated by repro: do not edit by hand
# Please edit Dockerfiles in {getOption('repro.dir')}/")
  to_write <- c(note, unlist(lapply(dockerfiles, xfun::read_utf8)))
  xfun::write_utf8(to_write, file)
}

automate_dir <- function(dir, warn = FALSE, create = !warn){
  if(missing(dir))dir <- getOption("repro.dir")
  dir_full <- usethis::proj_path(dir)
  exists <- fs::dir_exists(dir_full)
  if(!exists){
    if(warn){
      usethis::ui_oops("Directory {usethis::ui_code(dir)} does not exist!")
    }
    if(create){
      fs::dir_create(dir_full)
      usethis::ui_done("Directory {usethis::ui_code(dir)} created!")
      exists <- TRUE
    }
  }
  return(exists)
}

automate_load_packages <- function(){
  packages <- yaml_repro_current()$packages
  lapply(packages, library, character.only = TRUE, quietly = TRUE)
  return(invisible(NULL))
}

automate_load_scripts <- function(){
  paths <- lapply(yaml_repro_current()$scripts, usethis::proj_path)
  scripts <- lapply(paths, xfun::read_utf8)
  lapply(scripts, function(x)knitr::read_chunk(lines = x))
  return(invisible(NULL))
}

automate_load_data <- function(data, func, ..., assign = TRUE){
  which <- deparse(substitute(data))
  path <- usethis::proj_path(yaml_repro_current()$data[[which]])
  data <- do.call(func, list(path, ...))
  if(assign){
    assign(which, data, envir = .GlobalEnv)
    return(invisible(data))
  } else return(data)
}
